name: Deploy to Server

on: 
  push: 
    branches:
      - main  

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ vars.SSH_PORT }} -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy App via SSH
        run: |
          ssh -p ${{ vars.SSH_PORT }} ${{ vars.DEPLOY_USER }}@${{ vars.SERVER_IP }} << 'EOF'
            set -e  # Exit immediately if any command fails

            cd /home/abvsuacc/nextabvsu/abvsu-sikkim || exit 1

            git pull origin main

            npm install

            npm run build

            pm2 restart 4 || pm2 start npm --name "nextabvsu" -- start

            echo "Deployment complete."
          EOF